### ISSUE TITLE
Doctest syntax

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#100]
I just realized that Python actually uses `>>>` (three `>`s) for doctests, while we use `>>` since the dark ages of `doctest-for-matlab` (...:smile:) I don't remember if this was a concious decision; at any rate, I can't think of a good reason why `>>>` wasn't being used.

How about we add support for `>>>` (in which case `...` should be the appropriate continuation marker)?
We should likely retain the current syntax as an alternative..

**Comment by oheim** [comment]
The reason certainly is that `>>` is the default prompt of matlab (and also octave since 4.0.0) and therefore easily gets copied into such examples.

Using `>>>` probably is a bad idea, because it is used by the parser for highlighting syntax errors:

````
>> 3 + ...
> 4 i
parse error:

  syntax error

>>> 4 i
      ^
````

However, the use of `>>` within examples is very uncommon in Octave and Matlab (AFAIK). In the Matlab documentation input and output is mixed without clear separation of the two—you have to conclude from the context what the author wants to say. In the Octave manual and some packages I could find some examples using the old `octave:13>` prompt, some with TexInfo `@print{}`/`@result{}`, some without any output (and therefore without a marker for the input at all) and some without any separation between input and output (like Matlab).

After a quick look into several documentation pages I'd say that the symbolic package is the only (or at least a rare) candidate that uses `>>`.

**Comment by catch22** [comment]
Ah right - that was likely the reason (you can tell I haven't used Matlab for a while now). Maybe we'll then just stick with `>>` for the simple syntax.
