### ISSUE TITLE
Doctest skips `private` directories

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#121]
As noted in the `doctest_collect` code:
> % running code in private dirs may need mucking around with path

@catch22 said:
> In case we plan on this being a temporary behavior we should perhaps turn this into a warning.

I think Octave's `test` makes no special treatment of private directories.  That might be a bug in and of itself.  I had problems in `Symbolic` with tests in `private/`.

This is not urgent.  Are docs of private functions even accessible?  AFAICT, for `help some_priv_util` to work you have to be in the private dir or have it in your path to even access them.

**Comment by cbm755** [comment]
Here is the [upstream bug for `test`](https://savannah.gnu.org/bugs/?38776).  Also linked in our source code.  Perhaps a similar fix/workaround works for both `test` and `doctest`.

**Comment by oheim** [comment]
Since you cannot `get_help_text` for private functions, what is the use case of doctest'ing these?

**Comment by cbm755** [comment]
I tend to agree for `doctest`.  There is a use case for `test` on private (e.g., I write some utility, I write tests for it, then put it in `private/`).

For doctest, the only use case I can think of is a utility which is private but that you anticipate others might fork and use directly.  I can't be bothered developing for that case.  People can do some addpath hacks themselves if they want that.

@catch22, anything more compelling?  Otherwise, decision is not to support this.

**Comment by catch22** [comment]
Sorry guys, I am pretty busy currently, but will try to go through the issues and PRs tonight.

I'm usually documenting private functions and so they will have doctests, too. Here the "clients" are the developers of the library rather than its users. For example, I think it would be desirable to document & test the behavior of [doctest_compare.m](https://github.com/catch22/octave-doctest/blob/master/inst/private/doctest_compare.m) explicitly in that file.

Therefore I would suggest that we rather document it as a limitation that doctesting private functions is currently not supported (rather than decide that we do not want to support this in the future).

**Comment by catch22** [comment]
By the way, to be clear: Is this only about recursing into private folders (cf. the original `doctest_collect` discussion) or also about calling doctest explicitly on private files or folders?

**Comment by cbm755** [comment]
*cough* *cough* Actually at least in Octave it seems to recursive in private directories without problem.  Maybe all this pre-dates the "chdir" traversal we have now...

Anyway, I'm sorry for the noise: and I will update my PR.  In my defense, I started #116 to maintain the status quo ;-)

**Comment by catch22** [comment]
I am not sure what happened, but I like the result ;-)
