### ISSUE TITLE
tests can change the default output format options

### ISSUE THREAD

**Issue by mtmiller** [catch22/octave-doctest#183]
This is similar to #117. A test that uses the `format` function, for example, Octave's `chop` function, can break all subsequent tests that expect the default output format options to be set.

```
>> doctest camva
...
camva .................................................. PASS    5/5   
...
>> doctest chop
...
chop ................................................... FAIL    2/2   
...
>> doctest camva
...
camva .................................................. FAIL    2/5   
...
```

**Comment by cbm755** [comment]
Heh, I've seen this too: happy to see others running doctest on core! :-)

One option is just to declare in our documentation that doctests will be run with "format short" active.  Then we can safely do that at the top of each target.

Or maybe better, we query the current format and reset it after each target?

**Comment by cbm755** [comment]
Or we can ignore it and make "chop" clean up after itself?

**Comment by mtmiller** [comment]
I'm not sure there is a reliable way to get and reset the complete format state.

I like either of these two solutions
* declare that all doctests will be run with `format` (no args) as the starting state
* declare that doctests should not use the `format` function, or they should restore any settings that they change

**Comment by cbm755** [comment]
`help doctest` could say something like:
```
Using commands that change the global state (such as @code{chdir} or @code{format}) can influence tests that follow.  You may need to reset such changes at the end of your tests.
```

**Comment by cbm755** [comment]
Maybe more generally useful to have code that runs, but is hidden
```
@c doctest: +EXEC(format long g)
```
For example, I would use this to sort non deterministic output
```
x = ...
@c doctest: +EXEC(x = sort(x)
x ...
```

**Comment by catch22** [comment]
My 2 cents:
* I very much like the idea of documenting that all doctests are run under the default global state, so that tests that change it are responsible for cleaning it up (e.g., any `format xxx` should be reset by a call to `format`).
* Having said this, if the cleanup code is part of the doctest then it may not be when the test execution fails somewhere in the middle. If this turns out to be an issue, we could add a `+CLEANUP` directive that is promised to always be run, regardless of whether the test succeeds or fails.
* I feel that adding a general `+EXEC` directive may lead to situations where doctests no longer stand on their own. E.g., I could imagine that a novice user copy & pasting a doctest from the documentation and being confused about why the output is not the advertised one. So perhaps it's better to be explicit about any code that "canonicalizes" the output by sorting etc, at least as long as this does not get too much of a burden.
