### ISSUE TITLE
Allow +SKIP/+XFAIL depending on runtime condition

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#51]
We would like to be able to state things like that the doctest of `test_angle_brackets` is expected to fail for Octave versions <= 3.8.2. We could achieve this by some magic comment like

~~~
% >> s = test_angle_brackets()
% s = I <3 U
% XFAIL Octave<=3.8.2
~~~

but perhaps there is a simpler way?

**Comment by oheim** [comment]
If I understand correctly, the test fails because of a problem in `doctest` with Octave < 4. That should be no reason to mark tests as not working. You delegate a problem from one place to another and nobody (read: “not me” ;-) ) wants to maintain extra meta information for the documentation.

A version dependent discrimination should not be required, because all examples are intended for a particular Octave version: The core function examples must work with the containing Octave version, whereas package function examples must work with the minimum Octave version specified by the package's dependency.

However, there might be better reasons for saying that a certain doctest is known to fail. Or, even better, if a doctest is known to fail, it should be skipped in the first place. For example, in a package manual I have certain examples that I do not want to be tested, because it would mess up the testing environment or have unwanted side effects. For these cases it would be very good to declare the blocks as not to be doctest'ed. A magic marker within that block should be possible after a texinfo `@comment` (or simply `@c`). This way it can stay hidden from the user.

````
@example
@group
@comment SKIP_DOCTEST or whatever magic marker you find appropriate
pkg install -forge …
pkg load …
addpath (…)
system ('rm -rf …')
@end group
@end example
````

In your particular example with the angle brackets you should think about using a workaround (or at least trigger a warning inside doctest) if the octave version detected is < 4. Alternatively you could add an Octave >= 4 dependency in your package and don't think about it anymore.

**Comment by catch22** [comment]
My understanding is that the test fails due to a bug in Octave < 4.0, not due to a bug in doctest. So, in a perfect world, the `test_angle_brackets` test should become part of core Octave rather than doctest as to check that no future regressions are introduced.

I agree that we might want to either provide a workaround or depend on Octave>=4, though I don't have a sense of what is the better way to go (@cbm755? :smile:).

**Comment by cbm755** [comment]
+1 for some sort of SKIP_DOCTEST marker.  Python doctest has some notation for this: I'll check.  We should also support the plain text non-texinfo case.

> I agree that we might want to either provide a workaround or depend on Octave>=4,
> though I don't have a sense of what is the better way to go (@cbm755? :smile:).

Personally, I would do neither and just leave it as is for now.

Once the octave-stable-ppa thingy for ubuntu moves to Octave 4 then we can enable this in "make test"---as otherwise travis will fail.

**Comment by cbm755** [comment]
Python does this:
````
>>> p = Plot()                              # doctest: +SKIP
````
We might want to support that *AND* a quieter version for texinfo with `@comment`.

**Comment by catch22** [comment]
Something like this would be nice. I don't have much of an opinion on the syntax, though it would be nice if the syntax allowed for the addition of a conditional expression that determines the skip condition (e.g., `... +SKIP ~exist('sedumi');`). We don't have to implement that functionality right now, though.

**Comment by cbm755** [comment]
Sure, but also nice to match Python as close as possible...  I might work on this if I get a chance as I'd like this feature, but won't get to it immediately.

**Comment by catch22** [comment]
Yeah, I think the Python syntax would allow for possibly future extension.

**Comment by cbm755** [comment]
Started in #55, but no texinfo-specific stuff yet.

**Comment by catch22** [comment]
I've merged this one. Leaving this bug open until we resolve what to do with the angle bracket test.

**Comment by catch22** [comment]
Given #70, how about we provide an expression to evaluate after `+SKIP` and `+XFAIL` that determines whether the test is supposed to be skipped/supposed to fail? (Alternatively, `+SKIP_IF` and `+XFAIL_IF` if that is preferred?)

**Comment by cbm755** [comment]
I'm not sure of the pressing need for such a thing.  The main non-trivial* use that I can think of would for having 1. different output for Matlab or Octave, 2. different output per Octave version.

Leave it open, worry about it later?

*IMHO: angle bracket test is not worth engineering for: your plan to leave in `test/xfail/` is enough.

**Comment by catch22** [comment]
Yeah that's also the motivation that I would have. Ok let's postpone this.
